# Generated by Django 3.2.5 on 2021-11-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_cat_title_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_desc', models.TextField(default=None)),
                ('jobs_thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Portofolio_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_cat_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Portofolio_cat',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work_title', models.CharField(max_length=70)),
                ('work_desc', models.TextField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porto_title', models.CharField(max_length=50)),
                ('porto_thumbnail', models.ImageField(upload_to='phutos/%Y/%m/%d')),
                ('porto_cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='porto_category', to='blog.portofolio_cat')),
            ],
            options={
                'verbose_name_plural': 'Portofolio',
            },
        ),
    ]
