# Generated by Django 3.2.5 on 2021-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_jobs_portofolio_portofolio_cat_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='portofolio_cat',
            options={'verbose_name': 'Portofolio Category', 'verbose_name_plural': 'Portofolio Category'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_desc',
            field=models.TextField(default=None, null=True),
        ),
    ]
