# Generated by Django 3.2.5 on 2021-11-23 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_work_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='porto_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
