# Generated by Django 3.2.5 on 2022-01-12 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_portofolio_cat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='porto_thumbnail',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
