# Generated by Django 3.2.5 on 2022-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220112_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=50)),
                ('testimonial_title', models.CharField(max_length=70)),
                ('testimonial_img', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('testimonial_icon', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('testimonial_desc', models.TextField(blank=True, default=None)),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
    ]
