# Generated by Django 3.2.5 on 2022-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_featured',
            field=models.BooleanField(default=False),
        ),
    ]
